## Project: Customer Review NLP Analysis

### Description

This project demonstrates a basic Natural Language Processing (NLP) workflow using customer review data. The objective is to process unstructured text, extract meaningful information, and analyze customer sentiment.

The project follows a typical NLP pipeline that includes:

- Loading customer reviews from a CSV file
- Cleaning and preprocessing text data
- Tokenizing text into individual words
- Removing stop words
- Applying lemmatization
- Performing sentiment analysis
- Classifying reviews as Positive, Negative, or Neutral

By completing this project, I gained hands-on experience with fundamental NLP concepts and common Python NLP libraries. This workflow reflects how organizations can analyze customer feedback to better understand user opinions, identify common issues, and improve products or services.

### Objectives

- Understand the fundamentals of Natural Language Processing
- Learn how to preprocess and clean text data
- Apply tokenization and stop word removal techniques
- Use lemmatization to normalize words
- Perform sentiment analysis on customer reviews
- Generate insights from textual data

### Tools and Libraries Used

- Python
- Pandas
- NLTK
- TextBlob
- Regular Expressions (re)

### Expected Outcome

At the end of this project, customer reviews will be transformed from raw text into structured information that can be analyzed and interpreted. The final output includes sentiment scores, sentiment labels, and a processed dataset ready for further analysis.

In [1]:
# Load the customer reviews dataset

import pandas as pd

df = pd.read_csv("customer_reviews.csv")

df.head()

                                      review
0       This laptop is amazing and very fast
1               The battery life is terrible
2     Excellent customer service and support
3  The app keeps crashing and is frustrating
4        I love using this product every day

In [2]:
# Text Cleaning 

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    return text

df["clean_review"] = df["review"].apply(clean_text)

df[["review", "clean_review"]]

,review,clean_review
0,This laptop is amazing and very fast,this laptop is amazing and very fast
1,The battery life is terrible,the battery life is terrible
2,Excellent customer service and support,excellent customer service and support
3,The app keeps crashing and is frustrating,the app keeps crashing and is frustrating
4,I love using this product every day,i love using this product every day
5,Very poor experience and waste of money,very poor experience and waste of money
6,The interface is clean and easy to use,the interface is clean and easy to use
7,The product quality is disappointing,the product quality is disappointing

#### Observation

The text cleaning step converted all text to lowercase and removed punctuation and special characters. This made the text more consistent and easier to process. Cleaning text helps reduce noise and improves the quality of later NLP tasks such as tokenization and sentiment analysis.

In [3]:
# Tokenization

from nltk.tokenize import word_tokenize

df["tokens"] = df["clean_review"].apply(word_tokenize)

df[["clean_review", "tokens"]]

,clean_review,tokens
0,this laptop is amazing and very fast,"[this, laptop, is, amazing, and, very, fast]"
1,the battery life is terrible,"[the, battery, life, is, terrible]"
2,excellent customer service and support,"[excellent, customer, service, and, support]"
3,the app keeps crashing and is frustrating,"[the, app, keeps, crashing, and, is, frustrating]"
4,i love using this product every day,"[i, love, using, this, product, every, day]"
5,very poor experience and waste of money,"[very, poor, experience, and, waste, of, money]"
6,the interface is clean and easy to use,"[the, interface, is, clean, and, easy, to, use]"
7,the product quality is disappointing,"[the, product, quality, is, disappointing]"

#### Observation

The tokenization process split each review into individual words called tokens. This allows the text to be analyzed at the word level and prepares it for further processing such as stop word removal and lemmatization.

In [4]:
# Remove Stopwords

from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(tokens):
    return [
        word for word in tokens
        if word not in stop_words
    ]

df["filtered_tokens"] = df["tokens"].apply(remove_stopwords)

df[["tokens", "filtered_tokens"]]

,tokens,filtered_tokens
0,"[this, laptop, is, amazing, and, very, fast]","[laptop, amazing, fast]"
1,"[the, battery, life, is, terrible]","[battery, life, terrible]"
2,"[excellent, customer, service, and, support]","[excellent, customer, service, support]"
3,"[the, app, keeps, crashing, and, is, frustrating]","[app, keeps, crashing, frustrating]"
4,"[i, love, using, this, product, every, day]","[love, using, product, every, day]"
5,"[very, poor, experience, and, waste, of, money]","[poor, experience, waste, money]"
6,"[the, interface, is, clean, and, easy, to, use]","[interface, clean, easy, use]"
7,"[the, product, quality, is, disappointing]","[product, quality, disappointing]"

####
 Observation

Common words such as "is", "and", and "the" were removed from the reviews. These words occur frequently but often carry little meaning. Removing stop words helps focus on the most informative words in the text.

In [5]:
# Lemmatization

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_words(tokens):
    return [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

df["lemmatized"] = df["filtered_tokens"].apply(lemmatize_words)

df[["filtered_tokens", "lemmatized"]]

,filtered_tokens,lemmatized
0,"[laptop, amazing, fast]","[laptop, amazing, fast]"
1,"[battery, life, terrible]","[battery, life, terrible]"
2,"[excellent, customer, service, support]","[excellent, customer, service, support]"
3,"[app, keeps, crashing, frustrating]","[app, keep, crashing, frustrating]"
4,"[love, using, product, every, day]","[love, using, product, every, day]"
5,"[poor, experience, waste, money]","[poor, experience, waste, money]"
6,"[interface, clean, easy, use]","[interface, clean, easy, use]"
7,"[product, quality, disappointing]","[product, quality, disappointing]"

#### Observation

Lemmatization converted words into their base dictionary form. This helps group similar words together and reduces redundancy in the text. Compared to stemming, lemmatization produces more meaningful and readable words.

In [6]:
# Sentiment Analysis

from textblob import TextBlob

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

df["sentiment_score"] = df["review"].apply(get_sentiment)

df[["review", "sentiment_score"]]

                                      review  sentiment_score
0       This laptop is amazing and very fast             0.43
1               The battery life is terrible            -1.00
2     Excellent customer service and support             1.00
3  The app keeps crashing and is frustrating            -0.40
4        I love using this product every day             0.50
5    Very poor experience and waste of money            -0.36
6     The interface is clean and easy to use             0.40
7       The product quality is disappointing            -0.60

#### Observation

Sentiment analysis assigned a polarity score to each review. Positive reviews received positive scores, while negative reviews received negative scores. This demonstrates how NLP can be used to automatically understand customer opinions and feedback.

In [7]:
# Sentiment label

def sentiment_label(score):
    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

df["sentiment"] = df["sentiment_score"].apply(sentiment_label)

df[["review", "sentiment"]]

                                      review sentiment
0       This laptop is amazing and very fast  Positive
1               The battery life is terrible  Negative
2     Excellent customer service and support  Positive
3  The app keeps crashing and is frustrating  Negative
4        I love using this product every day  Positive
5    Very poor experience and waste of money  Negative
6     The interface is clean and easy to use  Positive
7       The product quality is disappointing  Negative

#### Observation

The sentiment scores were converted into labels: Positive, Negative, and Neutral. This makes the results easier to interpret and provides a simple way to categorize customer reviews.

In [8]:
# Summary of Sentiment Analysis

print("Total Reviews:", len(df))

print("\nSentiment Counts:")
print(df["sentiment"].value_counts())

Total Reviews: 8

Sentiment Counts:
sentiment
Positive    4
Negative    4
Name: count, dtype: int64

In [10]:
# Save results to a new CSV file

df.to_csv("processed_reviews.csv", index=False)

print("Processed file saved successfully")

Processed file saved successfully

## Final Observation

This notebook demonstrated a complete NLP workflow using customer reviews. The text was cleaned, tokenized, filtered, lemmatized, and analyzed for sentiment. The results show how raw text data can be transformed into structured insights using NLP techniques.

Leared Outcomes:

- Text preprocessing improves data quality.
- Tokenization breaks text into manageable units.
- Stop word removal focuses analysis on meaningful words.
- Lemmatization standardizes word forms.
- Sentiment analysis can automatically identify customer opinions.
- NLP can be applied to real-world tasks such as review analysis, customer feedback processing, and opinion mining.